using System;

namespace Prometheus.DotNetRuntime.EventListening.EventSources
{
    /// <summary>
    /// Provider name: System.Diagnostics.Eventing.FrameworkEventSource. Provides events generated by
    /// the CoreClr libraries. 
    /// </summary>
    public class FrameworkEventSource
    {
        public static readonly Guid Id = Guid.Parse("8e9f5090-2d75-4d03-8a81-e5afbf85daf1");
        
        [Flags]
        internal enum Keywords : long
        {
            Loader = 0x0001,
            ThreadPool = 0x0002,
            NetClient = 0x0004,
            DynamicTypeUsage = 0x0008,
            ThreadTransfer = 0x0010, 
        }
    }
}