using System;

namespace Prometheus.DotNetRuntime.EventListening.EventSources
{
    /// <summary>
    /// Provider name: Microsoft-AspNetCore-Server-Kestrel. Provides events generated by the .NET runtime (unmanaged code).
    /// </summary>
    public class KestrelEventSource
    {
        public static readonly Guid Id = Guid.Parse("bdeb4676-a36e-5442-db99-4764e2326c7d");
    }
}