using System;

namespace Prometheus.DotNetRuntime.EventListening.EventSources
{
    /// <summary>
    /// Provider name: System.Runtime. Provides counters generated by the .NET runtime.
    /// </summary>
    public class SystemRuntimeEventSource
    {
        public static readonly Guid Id = new ("49592C0F-5A05-516D-AA4B-A64E02026C89");
    }
}