{
 "title": "Debugging metrics",
 "description": "Displays internal debugging metrics generated by prometheus-net.DotNetRuntime when WithDebuggingMetrics() has been called at setup.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "dotnet_build_info" }
  ]
 },
 "panels": [
  {
   "title": "CPU use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval]) / process_cpu_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Events/ sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Events/ sec" }
   ],
   "targets": [
    {
     "expr": "sum (rate(dotnet_debug_event_count_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{listener_name}}"
    }
   ]
  },
  {
   "title": "Event processing time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dotnet_debug_event_seconds_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Processing time (s)"
    }
   ]
  },
  {
   "title": "Num threads producing events (by listener)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dotnet_debug_publish_thread_count{instance=\"$instance\"}",
     "legendFormat": "{{listener_name}}"
    }
   ]
  },
  { "title": "Volume of events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Events/ sec (by listener name)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Events/ sec" }
   ],
   "targets": [
    {
     "expr": "sum by (listener_name) (rate(dotnet_debug_event_count_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{listener_name}}"
    }
   ]
  },
  {
   "title": "Events/ sec (by event source name)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "Events/ sec" }
   ],
   "targets": [
    {
     "expr": "sum by (event_source_name) (rate(dotnet_debug_event_count_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{event_source_name}}"
    }
   ]
  },
  {
   "title": "Events (full breakdown)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "events/ sec" }
   ],
   "targets": [
    {
     "expr": "rate(dotnet_debug_event_count_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{listener_name}}:{{event_source_name}}/{{event_name}}"
    }
   ]
  },
  { "title": "Event processing time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Time consumed (by event listener)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (listener_name)(rate(dotnet_debug_event_seconds_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{listener_name}}"
    }
   ]
  },
  {
   "title": "Time consumed (by event source name)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (event_source_name)(rate(dotnet_debug_event_seconds_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{event_source_name}}"
    }
   ]
  }
 ]
}