{
 "title": ".NET runtime metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "dotnet_build_info" }
  ]
 },
 "panels": [
  { "title": "Current Application Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "% CPU consumption",
   "type": "singlestat",
   "description": "The percentage of available CPU resources consumed.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[$__interval]) / process_cpu_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "% Memory consumption",
   "type": "singlestat",
   "description": "The percentage of available memory resources consumed.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_working_set_bytes{instance=\"$instance\"} / dotnet_gc_memory_total_available_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "% Paused time",
   "type": "singlestat",
   "description": "The percentage of time that the application was paused to allow the garbage collector to run.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "dotnet_gc_pause_ratio{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "% GC CPU consumption",
   "type": "singlestat",
   "description": "The percentage of total process CPU utilization that was dedicated to performing garbage collections.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "dotnet_gc_cpu_ratio{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Thread pool queue length",
   "type": "singlestat",
   "description": "The average length of the thread pool's work queue. Values greater than 0 indicate a problem.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(dotnet_threadpool_queue_length_sum{instance=\"$instance\"}[$__rate_interval]))  / \nsum(rate(dotnet_threadpool_queue_length_count{instance=\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "% JIT CPU consumption",
   "type": "singlestat",
   "description": "The percentage of CPU utilization that was dedicated to compiling methods by the Just In Time (JIT) compiler.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "dotnet_jit_cpu_ratio{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Exceptions/ sec",
   "type": "singlestat",
   "description": "The rate of exceptions being thrown per second",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(dotnet_exceptions_total{instance=\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  { "title": "Memory / Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_working_set_bytes{instance=\"$instance\"}",
     "legendFormat": "# bytes (in physical memory)"
    },
    {
     "expr": "dotnet_gc_memory_total_available_bytes{instance=\"$instance\"}",
     "legendFormat": "Total bytes available (memory limit)"
    }
   ]
  },
  {
   "title": "Heap size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dotnet_gc_heap_size_bytes{instance=\"$instance\"}",
     "legendFormat": "gen {{gc_generation}}"
    }
   ]
  },
  {
   "title": "GC CPU + pause ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "dotnet_gc_cpu_ratio{instance=\"$instance\"}",
     "legendFormat": "GC CPU %"
    },
    {
     "expr": "dotnet_gc_pause_ratio{instance=\"$instance\"}",
     "legendFormat": "GC Pause %"
    }
   ]
  },
  {
   "title": "Number of GC collections/ sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dotnet_gc_collection_count_total{instance=\"$instance\"}[$__interval])) by (gc_generation, gc_reason)",
     "legendFormat": "gen {{gc_generation}}: {{gc_reason}}"
    }
   ]
  },
  {
   "title": "Bytes allocated (by heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dotnet_gc_allocated_bytes_total{instance=\"$instance\"}[$__interval])) by (gc_heap)",
     "legendFormat": "Alloc bytes {{gc_heap}}"
    }
   ]
  },
  {
   "title": "Average GC duration (by generation)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dotnet_gc_collection_seconds_sum{instance=\"$instance\"}[$__interval])) by (gc_generation) / sum(increase(dotnet_gc_collection_seconds_count{instance=\"$instance\"}[$__interval])) by (gc_generation) ",
     "legendFormat": "{{gc_generation}}"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(increase(dotnet_gc_collection_seconds_bucket{instance=\"$instance\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Thread pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Thread pool queue length",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (le) (increase(dotnet_threadpool_queue_length_bucket{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Num thread pool threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dotnet_threadpool_num_threads{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Num thread timers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dotnet_threadpool_timer_count{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Thread pool adjustment reasons",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dotnet_threadpool_adjustments_total{instance=\"$instance\"}[$__interval])) by (adjustment_reason )",
     "legendFormat": "{{adjustment_reason}}"
    }
   ]
  },
  { "title": "JIT compliation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Methods compiled/ sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dotnet_jit_method_total{dynamic=\"true\", instance=\"$instance\"}[$__interval])",
     "legendFormat": "Dynamic methods"
    },
    {
     "expr": "rate(dotnet_jit_method_total{dynamic=\"false\", instance=\"$instance\"}[$__interval])",
     "legendFormat": "Methods"
    }
   ]
  },
  {
   "title": "JIT CPU usage ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "dotnet_jit_cpu_ratio{instance=\"$instance\"}",
     "legendFormat": "% CPU utilization"
    }
   ]
  },
  { "title": "Contention", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Locks contended/ sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dotnet_contention_total{instance=\"$instance\"}[$__interval])",
     "legendFormat": "# Locks contended"
    }
   ]
  },
  {
   "title": "Time waiting for locks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(dotnet_contention_seconds_total{instance=\"$instance\"}[$__interval])",
     "legendFormat": "Waiting time"
    }
   ]
  },
  { "title": "Exceptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Exceptions/ sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dotnet_exceptions_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}