{
 "title": ".NET runtime metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Current Application Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "% GC CPU consumption",
   "type": "singlestat",
   "description": "The percentage of total process CPU utilization that was dedicated to performing garbage collections.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    { "expr": "dotnet_gc_cpu_ratio" }
   ]
  },
  {
   "title": "% Paused time",
   "type": "singlestat",
   "description": "The percentage of time that the application was paused to allow the garbage collector to run.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    { "expr": "dotnet_gc_pause_ratio" }
   ]
  },
  {
   "title": "% JIT CPU consumption",
   "type": "singlestat",
   "description": "The percentage of CPU utilization that was dedicated to compiling methods by the Just In Time (JIT) compiler.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    { "expr": "dotnet_jit_cpu_ratio" }
   ]
  },
  {
   "title": "Thread pool scheduling latency",
   "type": "singlestat",
   "description": "The delay between when a job is scheduled for execution on the thread pool and when it starts execution. Measurement taken from the 90th percentile.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(dotnet_threadpool_scheduling_delay_seconds_bucket[$__interval])) by (le))"
    }
   ]
  },
  { "title": "Memory / Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Heap size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "dotnet_gc_heap_size_bytes", "legendFormat": "gen {{gc_generation}}" }
   ]
  },
  {
   "title": "Bytes allocated (by heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dotnet_gc_allocated_bytes_total{gc_heap=\"loh\"}[$__interval])) by (gc_heap)",
     "legendFormat": "Large object heap (objects > 85KB)"
    },
    {
     "expr": "sum(rate(dotnet_gc_allocated_bytes_total{gc_heap=\"soh\"}[$__interval])) by (gc_heap)",
     "legendFormat": "Small object heap"
    }
   ]
  },
  {
   "title": "GC CPU + pause ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "dotnet_gc_cpu_ratio", "legendFormat": "GC CPU %" },
    { "expr": "dotnet_gc_pause_ratio", "legendFormat": "GC Pause %" }
   ]
  },
  {
   "title": "Number of GC collections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dotnet_gc_collection_seconds_count[$__interval])) by (gc_generation, gc_type)",
     "legendFormat": "gen {{gc_generation}}: {{gc_type}}"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(dotnet_gc_collection_seconds_bucket[$__interval])) by (le))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(dotnet_gc_collection_seconds_bucket[$__interval])) by (le))",
     "legendFormat": "90th %"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(dotnet_gc_collection_seconds_bucket[$__interval])) by (le))",
     "legendFormat": "99th %"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(dotnet_gc_collection_seconds_bucket[$__interval])) by (le))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Average GC duration (by generation)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dotnet_gc_collection_seconds_sum[$__interval])) by (gc_generation) / sum(increase(dotnet_gc_collection_seconds_count[$__interval])) by (gc_generation) ",
     "legendFormat": "{{gc_generation}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Num thread pool threads",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "dotnet_threadpool_num_threads" }
   ]
  },
  {
   "title": "Thread pool scheduling latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(dotnet_threadpool_scheduling_delay_seconds_bucket[$__interval])) by (le))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(dotnet_threadpool_scheduling_delay_seconds_bucket[$__interval])) by (le))",
     "legendFormat": "90th %"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(dotnet_threadpool_scheduling_delay_seconds_bucket[$__interval])) by (le))",
     "legendFormat": "99th %"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(dotnet_threadpool_scheduling_delay_seconds_bucket[$__interval])) by (le))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Thread pool adjustment reasons",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dotnet_threadpool_adjustments_total[$__interval])) by (adjustment_reason )",
     "legendFormat": "{{adjustment_reason}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {}
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(increase(dotnet_gc_collection_seconds_bucket[$__interval])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.5, sum(increase(dotnet_gc_collection_seconds_bucket[$__interval])) by (le))"
    },
    {
     "expr": "histogram_quantile(1.0, sum(increase(dotnet_gc_collection_seconds_bucket[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(dotnet_gc_collection_seconds_bucket[10m])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(dotnet_gc_collection_seconds_bucket[10m])) by (le))"
    }
   ]
  },
  {
   "title": "Heap size (all generations)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 68 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(dotnet_gc_heap_size_bytes)" }
   ]
  }
 ]
}