name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100'
    - run: dotnet test -c "DebugV2" src/prometheus-net.DotNetRuntime.sln
    - run: dotnet test -c "DebugV3" src/prometheus-net.DotNetRuntime.sln
